### ISSUE TITLE
Add example per property

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas.github.io#57]
During our meeting on Thu & Fri last week, we found sometimes confusing or time consuming going through full examples. Having one (or two) mini examples per property could help clarify things. Is is possible to add a new column to specifications where these mini examples are added?

Some of the attendees were @ficolo @rajido @ricardoaat @Kerruba Matt and Petr.

**Comment by profgiuseppe** [comment]
This was something that came up also during our workshop in Italy, see BioSchemas/specifications#130

**Comment by kcmcleod** [comment]
closing as issue already exists in appropriate repo

**Comment by ljgarcia** [comment]
Hi @kcmcleod what would be that repo? Do you mean specifications? I would say examples, either full or partial (by property) should be available for everybody on the main website... I would not ask end-users to dig into our specs folder.

**Comment by ricardoaat** [comment]
Hi @ljgarcia,
i've created a PR addressing this issue, please give it a look https://github.com/BioSchemas/bioschemas.github.io/pull/60

This issue is in the appropriated repo, the idea is to use only BioSchemas/specifications project for new issues, thus having them centralized.

Let me know what you think, so i can merge the PR
